import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

const dmSans = localFont({
  src: [
    {path: '../fonts/DMSans-Regular.ttf', weight:"400"},
    {path: '../fonts/DMSans-Medium.ttf', weight:"500"},
    {path: '../fonts/DMSans-SemiBold.ttf', weight:"600"},
    {path: '../fonts/DMSans-Bold.ttf', weight:"700"},
  ],
  variable:'--dm'
})

const openSans = localFont({
  src: [
    {path: '../fonts/OpenSans-Regular.ttf', weight:"400"},
    {path: '../fonts/OpenSans-Medium.ttf', weight:"500"},
    {path: '../fonts/OpenSans-SemiBold.ttf', weight:"600"},
    {path: '../fonts/OpenSans-Bold.ttf', weight:"700"},
  ],
  variable:'--open'
})

const nunitoSans = localFont({
  src: [
    {path: '../fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf'},
  ],
  variable:'--nunito'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.variable} ${openSans.variable} ${nunitoSans.variable}`}>
      <body className="font-open" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
